<?php $this->jQuery()
           ->addJavascriptFile($this->baseUrl.'/js/jquery/jqgrid/js/i18n/grid.locale-es.js') 
           ->addJavascriptFile($this->baseUrl.'/js/jquery/jqgrid/js/jquery.jqGrid.min.js')
           ->addStylesheet($this->baseUrl."/js/jquery/jqgrid/css/ui.jqgrid.css") ; ?>

<div class="titulo"><?php echo $this->titulo ?></div>
<div id="divLista">
    <div id="divBotonera">
        
        <?php if(!$this->btnEliminarOcultar): ?>
            <a href='#' id='btnDel' >Extraer desde el archivador</a>
        <?php endif; ?>
    </div>
    <div id="divBuscar">
    <? /* Botón Buscar para el jqgrid */ ?>
    <input type="text" placeholder='Digite texto a buscar' id="txtBusqueda" value="" size="20" />
    <a id="myButtonBuscar" onclick="gridReload()" href="#" >Buscar</a>
    </div>

    <table id="list" ></table>
    <div id="pager" ></div>
</div>
<script type="text/javascript">

    jQuery("#list").jqGrid({
            url:'<?php echo $this->baseUrlController ?>/listararchivados/',
            datatype: "json",
            colNames:[<?php echo $this->colNames ?>],
            colModel:[
                    <?php echo $this->colModel ?>
            ],
            rowNum:25,
            height:"400",
            autowidth: true,
            pager: '#pager',
            sortname: '<? echo $this->sortName ?>',
        viewrecords: true,
        multiselect: true, /* Permito que se seleccionen varios registros */
        sortorder: "desc",
        loadError : function(xhr,st,err) {
            jQuery("#rsperror").html("Type: "+st+"; Response: "+ xhr.status + " "+xhr.statusText+"; Error: "+err);
        }
    });

</script>
<script type="text/javascript">
/*    parent.menu.document.getElementById('procesando').innerHTML = ''    */
    /*
     * Entorno de configuración para el grid
     **/

     /* Oculto campos */
     jQuery("#list").jqGrid('hideCol',[<?php echo $this->hideCol ?>]); /* Para ocultar columnas, pueden agregarse estas separadas por comas */

    /* Agrego estilo a los botones */
    $("#myButtonBuscar").button({
        icons: {
        primary: 'ui-icon-search'
        }
    })

    $("#btnDel").button({
        icons: {
        primary: 'ui-icon-arrowreturnthick-1-w'
        }
    })

    /* Función que recarga el grid.  Es llamada desde el botón Buscar */
    function gridReload(){
        var txtBuscar = jQuery("#txtBusqueda").val();
        jQuery("#list").jqGrid('setGridParam',{url:'<?php echo $this->baseUrlController ?>/listararchivados/txtBuscar/'+txtBuscar,page:1}).trigger("reloadGrid");
    }

    function editaDesdeLink(id){

        <?php if($this->editarSinDialog): ?>

            document.location = '<?php echo $this->baseUrlController ?>/editar/id/'+id;

        <?php else: ?>

            /* Asigno nuevo Título a la ventana que se abrirá */
            $("#wndEdicion").dialog("option", "title", '<?php echo $this->titulo ?> [Edición]');

            /* Cargo en el div la página que deseo */
            $("#wndEdicion").load('<?php echo $this->baseUrlController ?>/editar/id/'+id);

            /* Abro la ventana */
            setTimeout(function(){ $("#wndEdicion").dialog('open') }, 100);

        <?php endif; ?>

    }

    $(function() {

        /* Focus en Búsqueda */
        $("#txtBusqueda").focus();

        /* Para activar búsquedas con tecla enter */
        $("#txtBusqueda").keypress(function(e){
            if (e.which == 13) { /* Si ha presionado la tecla enter */
                gridReload();
            }
        });

        /* Agrego en la barra inferior solo el botón Recargar */
        jQuery("#list").jqGrid('navGrid','#pager',{edit:false,add:false,del:false,search:false});

        /* Configuro la ventana de Edición */
        $("#wndEdicion").dialog({
                title: "Edición",
                modal: true,
                autoOpen: false,
                width: <? echo $this->widthDialog; ?>,
                height: 'auto',
                buttons: {
                    Cerrar: function() {
			$(this).dialog('close');
                    }
		}
         });

        /* Asgino métodos a los botones */
        /* Botón Nuevo */
        // Para llamar al formulario en una página normal sin ventana Dialog.
        // en el action 'agregar' debe colocarse comentario a la línea $this->_helper->layout->disableLayout();
	// $("#btnNew").click(function() {
        //    document.location = '<?php // echo $this->baseUrlController ?>/agregar/';
        // });

	$("#btnEdt").click(function() {
            var id = jQuery("#list").jqGrid('getGridParam','selrow');
            if( id != null ) {

                <?php if($this->editarSinDialog): ?>

                    document.location = '<?php echo $this->baseUrlController ?>/agregar/';

                <?php else: ?>

                     /* Asigno nuevo Título a la ventana que se abrirá */
                    $("#wndEdicion").dialog("option", "title", '<?php echo $this->titulo ?> [Editar]');

                    /* Cargo en el div la página que deseo */
                    $("#wndEdicion").load('<?php echo $this->baseUrlController ?>/editar/id/'+id);

                    /* Abro la ventana */
                    setTimeout(function(){ $("#wndEdicion").dialog('open') }, 100);

                <?php endif; ?>
            } else {
                MyAlert("Seleccione el registro a Editar!");
            }

        });

        $("#btnDelXXXX").click(function(){
            var arrSelected = jQuery("#list").jqGrid('getGridParam','selarrrow'); /* Devuelve array con los id de todos los registros seleccionados */
            if( arrSelected.length > 0 ) {
                jConfirm('¿ Está seguro de extraer este(os) Docuemnto(s) ?', 'Dialogo de Confirmación', function(ok) {
                    if(ok){
                        $.ajax({
                                type: "POST",
                                url: "<?php echo $this->baseUrlController ?>/eliminar/id/"+arrSelected,
                                success: function(datos){
                                    var result = datos.split("|");
                                    if (result[0] == "error"){
                                        MyAlert("ERROR: " + result[1])
                                        return false
                                    }
                                    gridReload()
                                }
                        });
                    }
                });
            } else {
                MyAlert("Seleccione el(los) registro(s) que va a extraer desde su archivador!");
            }

        });


	$("#btnDel").click(function() {
            var arrSelected = jQuery("#list").jqGrid('getGridParam','selarrrow'); /* Devuelve array con los id de todos los registros seleccionados */ 
            
            if( arrSelected.length > 0 ) {

                    $.ajax({
                            type: "POST",
                            url: "<?php echo $this->baseUrlController ?>/devolverdearchivo/id/"+arrSelected,
                            success: function(datos){
                                var result = datos.split("|");
                                if (result[0] == "error"){
                                    MyAlert("ERROR: " + result[1])
                                    return false
                                }
                                gridReload()
                            }
                    });

            } else {
                MyAlert("Seleccione el(los) registro(s) que va a extraer desde su archivador!");
            }

        });


    });

</script>
<div id="wndEdicion"></div>