<?php $this->jQuery()
           ->addJavascriptFile($this->baseUrl.'/js/jquery/jqgrid/js/i18n/grid.locale-es.js') 
           ->addJavascriptFile($this->baseUrl.'/js/jquery/jqgrid/js/jquery.jqGrid.min.js')
           ->addStylesheet($this->baseUrl."/js/jquery/jqgrid/css/ui.jqgrid.css") ; ?>

<div class="titulo"><?php echo $this->titulo ?></div>
<div id="divLista">
    
    <div class='ui-widget ui-widget-content ui-corner-all' style="width: 800px;">
    <? /* Botón Buscar para el jqgrid */ ?>
        <? echo $this->form ?> 
    </div>

    <table id="list" ></table>
    <div id="pager" ></div>
</div>
<script type="text/javascript">

    jQuery("#list").jqGrid({
            url:'<?php echo $this->baseUrlController ?>/listarporbuscar/',
            datatype: "json",
            colNames:[<?php echo $this->colNames ?>],
            colModel:[
                    <?php echo $this->colModel ?>
            ],
            rowNum:25,
            height:"400",
            autowidth: true,
            pager: '#pager',
            sortname: '<? echo $this->sortName ?>',
        viewrecords: true,
        sortorder: "desc",
        onSelectRow: function(id){
            rowdata = jQuery("#list").getRowData(id);    
            $('#txtDocumentoId').val(rowdata.documento_id);
	},        
        loadError : function(xhr,st,err) {
            jQuery("#rsperror").html("Type: "+st+"; Response: "+ xhr.status + " "+xhr.statusText+"; Error: "+err);
        }
    });

</script>
<script type="text/javascript">
/*    parent.menu.document.getElementById('procesando').innerHTML = ''    */
    /*
     * Entorno de configuración para el grid
     **/

     /* Oculto campos */
     jQuery("#list").jqGrid('hideCol',[<?php echo $this->hideCol ?>]); /* Para ocultar columnas, pueden agregarse estas separadas por comas */

    /* Agrego estilo a los botones */
    $("#buscar").button({
        icons: {
        primary: 'ui-icon-search'
        }
    })

    /* Función que recarga el grid.  Es llamada desde el botón Buscar */
    function gridReload(){
        
        var vExpediente_id = jQuery("#expediente_id").val();
        
        var vFechaDesde = jQuery("#fecha_desde").val();
        var vFechaHasta = jQuery("#fecha_hasta").val();
        
        var vTipo_documento_id = jQuery("#tipo_documento_id").val();
        var vFirma = jQuery("#firma").val();        
        var vAsunto = jQuery("#asunto").val();
        
        jQuery("#list").jqGrid('setGridParam',{url:'<?php echo $this->baseUrlController ?>/listarporbuscar/expediente_id/'+vExpediente_id+'/fecha_desde/'+vFechaDesde+'/fecha_hasta/'+vFechaHasta+'/tipo_documento_id/'+vTipo_documento_id+'/firma/'+vFirma+'/asunto/'+vAsunto,page:1}).trigger("reloadGrid");        
    }

    $(function() {

        /* A todos los objetos que tengan la clase datePickerUi los convierto en datepicker de JqueryUI */
        $(".datePickerUi").datepicker({dateFormat: 'dd-mm-yy',
                                            changeMonth: true,
                                            changeYear: true,
                                            showOn: 'button',
                                            buttonImage: '<?php echo $this->baseUrl.'/css/images/calendario.gif'; ?>',
                                            buttonImageOnly: true
                                            });


        /* Agrego en la barra inferior solo el botón Recargar */
        jQuery("#list").jqGrid('navGrid','#pager',{edit:false,add:false,del:false,search:false});

        /* Configuro la ventana de Edición */
        $("#wndEdicion").dialog({
                title: "Edición",
                modal: true,
                autoOpen: false,
                width: <? echo $this->widthDialog; ?>,
                height: 'auto',
                buttons: {
                    Cerrar: function() {
			$(this).dialog('close');
                    }
		}
         });

        $("#btnRecibir").click(function(){
            var arrSelected = jQuery("#list").jqGrid('getGridParam','selarrrow'); /* Devuelve array con los id de todos los registros seleccionados */
            if( arrSelected.length > 0 ) {
                jConfirm('¿ Está seguro de Recibir este(os) Documento(s) ?', 'Dialogo de Confirmación', function(ok) {
                    if(ok){
                        $.ajax({
                                type: "POST",
                                url: "<?php echo $this->baseUrlController ?>/recibir/id/"+arrSelected,
                                success: function(datos){
                                    var result = datos.split("|");
                                    if (result[0] == "error"){
                                        MyAlert("ERROR: " + result[1])
                                        return false
                                    }
                                    gridReload()
                                }
                        });
                    }
                });
            } else {
                MyAlert("Seleccione el(los) documento(s) que va a recibir!");
            }

        });


    });

</script>
<div id="wndEdicion"></div>