<?php $this->LoadFilesForm(array('ui.datepicker')); ?>
<?php echo $this->form ?>
<script type="text/javascript">

    $().ready(function() {
        
        /* A todos los objetos que tengan la clase datePickerUi los convierto en datepicker de JqueryUI */
        $(".datePickerUi").datepicker({dateFormat: 'dd-mm-yy',
                                            changeMonth: true,
                                            changeYear: true,
                                            showOn: 'button',
                                            buttonImage: '<?php echo $this->baseUrl.'/css/images/calendario.gif'; ?>',
                                            buttonImageOnly: true
                                            });
                                            
        $(".datePickerUi").mask("99-99-9999");                                            

        /* Setfocus */

        //asignamos el plugin ajaxForm al formulario frmEditar
/* SE USABA ANTES (NO DEJABA EL CURSOR EN EL CAMPO CUANDO ESTE ERA REQUERIDO)
 *                $('#frmEditar').ajaxForm({
            beforeSubmit: validarForm, //funcion que se ejecuta antes de enviar el form
            success: recibeRespuesta //funcion que se ejecuta una vez enviado el formulario
        }) ;
*/
        /* Para resaltar los input que son validados como requeridos.
         * Son resaltados en base a una clase de jquery-ui para que
         * se adapte el color a cualquier theme elegido.
         * */
        $.validator.setDefaults({
                highlight: function(input) {
                        $(input).addClass("ui-state-highlight");
                },
                unhighlight: function(input) {
                        $(input).removeClass("ui-state-highlight");
                }
        });

        $("#frmEditar").validate({
            submitHandler: function(form) {
                $(form).ajaxSubmit({
                      beforeSubmit: validarForm, //funcion que se ejecuta antes de enviar el form
                      success: recibeRespuesta //funcion que se ejecuta una vez enviado el formulario
                });
            }
        })

        /* Aplico estilo al botón guardar */
        $("#guardar").button();

//        $("#frmEditar").validate();

        /* Si estamos editando y el usua_id del registro es diferente a la usua_id de session, oculto el botón guardar */
        <?php if($this->usua_idregistro and $this->usua_idregistro <> $this->usua_idsession):  ?>        
            $("#guardar").hide();
        <?php endif;?>



    });

</script>