<?php $this->LoadFilesForm(array('ui.datepicker')); ?>
<?php echo $this->form ?>
<script type="text/javascript">

    $().ready(function() {
        
        $("#<?php echo $this->fieldFocus; ?>").focus();        
        
        /* Para resaltar los input que son validados como requeridos.
         * Son resaltados en base a una clase de jquery-ui para que
         * se adapte el color a cualquier theme elegido.
         * */
        $.validator.setDefaults({
                highlight: function(input) {
                        $(input).addClass("ui-state-highlight");
                },
                unhighlight: function(input) {
                        $(input).removeClass("ui-state-highlight");
                }
        });

        $("#frmEditar").validate({
            submitHandler: function(form) {
                $(form).ajaxSubmit({
                      beforeSubmit: validarForm, //funcion que se ejecuta antes de enviar el form
                      success: recibeRespuesta //funcion que se ejecuta una vez enviado el formulario
                });
            }
        })

        $("#frmEditarHijo").validate({
            submitHandler: function(form) {
                $(form).ajaxSubmit({
                      beforeSubmit: validarForm, //funcion que se ejecuta antes de enviar el form
                      success: recibeRespuestaCustom //funcion que se ejecuta una vez enviado el formulario
                });
            }
        })

        function recibeRespuestaCustom(responseText){
            frmEnviado = false;
             /* responseText es la variable que recibe lo que envía el server */
            var result = responseText.split("|");
            if (result[0] == "error"){
                MyAlert("ERROR: " + result[1])
                return false
            }
            /* Cierro la ventana dialog  */
            $(this).text("");     
            $('#wndNewOpcion').dialog('close');
            muestraDato(responseText);
        };


        /* Aplico estilo al botón guardar */
        $("#guardarEntidad").button();

        /* Si estamos editando y el usua_id del registro es diferente a la usua_id de session, oculto el botón guardar */
        <?php if($this->usua_idregistro and $this->usua_idregistro <> $this->usua_idsession):  ?>        
            $("#guardar").hide();
        <?php endif;?>



    });

</script>