<?php $this->LoadFilesForm(); ?>

<div class="titulo"><?php echo $this->titulo ?></div>

<div class='ui-widget ui-widget-content ui-corner-all' style="width: 800px;">
<?php echo $this->form ?>
</div>
<script type="text/javascript">

    $().ready(function() {

        /* Setfocus */

        //asignamos el plugin ajaxForm al formulario frmEditar
        /* Para resaltar los input que son validados como requeridos.
         * Son resaltados en base a una clase de jquery-ui para que
         * se adapte el color a cualquier theme elegido.
         * */
        $.validator.setDefaults({
                highlight: function(input) {
                        $(input).addClass("ui-state-highlight");
                },
                unhighlight: function(input) {
                        $(input).removeClass("ui-state-highlight");
                }
        });

        $("#frmEditar").validate({
            submitHandler: function(form) {
                $(form).ajaxSubmit({
                      beforeSubmit: validarForm, //funcion que se ejecuta antes de enviar el form
                      success: recibeRespuestaSinDialog //funcion que se ejecuta una vez enviado el formulario
                });
            }
        })

        $("#btnRegresar").button();
        /* Aplico estilo al botón guardar */
        $("#guardar").button();

//        $("#frmEditar").validate();

        /* Si estamos editando y el usua_id del registro es diferente a la usua_id de session, oculto el botón guardar */
        <?php if($this->usua_idregistro and $this->usua_idregistro <> 1):  ?>
            $("#guardar").hide();
        <?php endif;?>

        <?php // Muestro imágen guardada  ?>
        if($('#imagenHidden').val()){
            $("#imgLogo").attr("src","/uploads/" + $('#imagenHidden').val());            
        }    

    });

    function recibeRespuestaSinDialog (responseText){
         /* responseText es la variable que recibe lo que envía el server */
        var result = responseText.split("|");

        if (result[0] == "error"){
            MyAlert("ERROR: " + result[1])
            return false
        }

        document.location = '<?php echo $this->baseUrlController ?>/editar/';

    };


</script>