<?php $this->LoadFilesForm(array('ui.datepicker')); ?>
<div class="titulo"><?php echo $this->titulo ?></div>


<div class='ui-widget ui-widget-content ui-corner-all' style="width: 800px;">
    <div id="divBotonera">

        <a id ="btnRegresar" href="<?php echo $this->url(array('controller' => 'plantillas',
                                        'action' => 'poratender'));?>">Regresar</a>
    </div>
    
    <div id="dialog" title="Documento" >
    <?php echo $this->form ?>
    </div>
</div>    
    
<?php $this->headScript()->appendFile($this->baseUrl.'/js/tiny_mce/tiny_mce.js'); ?>

<script type="text/javascript">

    $().ready(function() {

        /* Muestro objeto para seleccionar o editar destino */
        
        $('#para_destino-element').append("<a id='seleccionaDestino' href='#'>Elegir de lista</a>");            
        $('#dependencia_iddestino-element').append("<a id='editaDestino' href='#'>Editar</a>");
        
	$("#editaDestino").click(function() {
            $("#para_destino-element").show();        
            $("#para_destino-label").show();        
            $("#para_destino").focus();
            
            $("#dependencia_iddestino-label").hide();        
            $("#dependencia_iddestino-element").hide();        
            $("#dependencia_iddestino").val('');
            
        });


	$("#seleccionaDestino").click(function() {
            $("#dependencia_iddestino-label").show();        
            $("#dependencia_iddestino-element").show();        

            $("#para_destino-label").hide();        
            $("#para_destino-element").hide();        
            $("#para_destino").val('');

        });


        $("#dependencia_iddestino").change(function() {
            
            dependencia_iddestino = $(this).val();
            
            $.ajax({
                    type: "POST",
                    url: "<?php echo $this->base ?>/gidoc/documentos/obtienedatosdestino/",
                    data: "dependencia_iddestino="+dependencia_iddestino,
                    success: function(datos){
                        var result = datos.split("|"); /*Recibo el mensaje desde el server */
                        $('#dependencia_destino').val(result[0])                
                        $('#cargo_destino').val(result[1])
                    }
            });            

        })


        <?php if($this->usua_idregistro):  ?>   /* Si estoy editando el registro */      
            
            dependencia_iddestino = $("#dependencia_iddestino").val();

            if(dependencia_iddestino){
                $("#seleccionaDestino").click(); 
            } else {
                $("#editaDestino").click();
            }

        <?php else: ?>        
            
            $("#seleccionaDestino").click(); 
            
        <?php endif; ?>
        /* FIN: Muestro objeto para seleccionar o editar destino */

        /* Aplicando ventana de dialogo al formulario */
        /*
        $( "#dialog" ).dialog({
            height: 450,
            width: 700
        });
    
        $('#dialog').closest('.ui-dialog').find('.ui-dialog-titlebar-close').remove();      
        */
        /* */

        tinyMCE.init({
		// General options
                language : "es",
                relative_urls: false,
                mode : "exact",
                elements : "cuerpo",
		theme : "advanced",
		skin : "o2k7",
		plugins : "phpimage,lists,table,advlink,emotions,inlinepopups,preview,print,contextmenu,fullscreen",

		// Theme options
		theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,forecolor,backcolor",
		theme_advanced_buttons2 : "link,unlink,anchor,phpimage,code,|,tablecontrols,|,hr,removeformat,|,sub,sup,|,charmap,emotions,|,print,|,fullscreen",
		theme_advanced_buttons3 : "",                
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_resizing : true,

		// Drop lists for link/image/media/template dialogs
		template_external_list_url : "lists/template_list.js",
		external_link_list_url : "lists/link_list.js",
		external_image_list_url : "lists/image_list.js",
		media_external_list_url : "lists/media_list.js"

	});



        $("#btnRegresar").button({
        })

        /* Setfocus */

        /* Para resaltar los input que son validados como requeridos.
         * Son resaltados en base a una clase de jquery-ui para que
         * se adapte el color a cualquier theme elegido.
         * */
        $.validator.setDefaults({
                highlight: function(input) {
                        $(input).addClass("ui-state-highlight");
                },
                unhighlight: function(input) {
                        $(input).removeClass("ui-state-highlight");
                }
        });

        /* Aplico estilo al botón guardar */
        $("#guardar").button();

//        $("#frmEditar").validate();
        $("#frmEditar").validate({
            ignore: ':hidden'
        })
        

        /* Si estamos editando y el usua_id del registro es diferente a la usua_id de session, oculto el botón guardar */
        <?php if($this->usua_idregistro and $this->usua_idregistro <> $this->usua_idsession):  ?>        
            $("#guardar").hide();
        <?php endif;?>


    });

</script>