<?php $this->jQuery()
           ->addJavascriptFile($this->baseUrl.'/js/jquery/jqgrid/js/i18n/grid.locale-es.js') 
           ->addJavascriptFile($this->baseUrl.'/js/jquery/jqgrid/js/jquery.jqGrid.min.js')
           ->addStylesheet($this->baseUrl."/js/jquery/jqgrid/css/ui.jqgrid.css") ; ?>
<?php $this->LoadFilesForm(array('')); ?>

<style>
#divObjPadre {
    font-size: 12px;
    margin-bottom: 10px;
}

.container {
display: table;
}

.row {
display: table-row;
}

.cell {
display: table-cell;
width: 150px;
border: 1px solid #d0e5f5 ;
padding: 0.5em;
text-align: right;
}

</style>

<br>
<div class="titulo"><?php echo $this->titulo ?></div>
<div id="divObjPadre">
    
    <div class="container">
        <div class="row">
            <div class="cell">Usuario:</div>
            <div class="cell"><?php echo $this->objPadre->usuario; ?></div>
        </div>
    </div>
    
</div>

<div id="divLista">
    <div id="divBotonera">
        
        <?php if(!$this->btnNuevoOcultar): ?>
            <a href='#' id='btnNew' >Nuevo</a>
        <?php endif; ?>

        <?php if(!$this->btnEliminarOcultar): ?>
            <a href='#' id='btnDel' >Eliminar</a>
        <?php endif; ?>

    </div>
    <div id="divBuscar">
    <? /* Botón Buscar para el jqgrid */ ?>
    <input type="text" placeholder='Digite texto a buscar' id="txtBusqueda" value="" size="20" />
    <a id="myButtonBuscar" onclick="gridReload()" href="#" >Buscar</a>
    </div>
    
    <table id="list" ></table>
    <div id="pager" ></div>
</div>
<script type="text/javascript">

    jQuery("#list").jqGrid({
            url:'<?php echo $this->baseUrlController ?>/listar/padre_id/<?php echo $this->objPadre->id ?>',
            datatype: "json",
            colNames:[<?php echo $this->colNames ?>],
            colModel:[
                    <?php echo $this->colModel ?>
            ],
            rowNum:25,
            height:"200",
            autowidth: true,
            pager: '#pager',
            sortname: '<? echo $this->sortName ?>',
        viewrecords: true,
        multiselect: true, /* Permito que se seleccionen varios registros */
        sortorder: "desc",
        loadError : function(xhr,st,err) {
            jQuery("#rsperror").html("Type: "+st+"; Response: "+ xhr.status + " "+xhr.statusText+"; Error: "+err);
        }
    });

</script>
<script type="text/javascript">
/*    parent.menu.document.getElementById('procesando').innerHTML = ''    */
    /*
     * Entorno de configuración para el grid
     **/

     /* Oculto campos */
     jQuery("#list").jqGrid('hideCol',[<?php echo $this->hideCol ?>]); /* Para ocultar columnas, pueden agregarse estas separadas por comas */

    /* Agrego estilo a los botones */
    $("#myButtonBuscar").button({
    })

    $("#btnNew").button({
    })

/*
    $("#btnEdt").button({
        icons: {
        primary: 'ui-icon-pencil'
        }
    })
*/

    $("#btnDel").button({
    })

    /* Función que recarga el grid.  Es llamada desde el botón Buscar */
    function gridReload(){
        var txtBuscar = jQuery("#txtBusqueda").val();
        jQuery("#list").jqGrid('setGridParam',{url:'<?php echo $this->baseUrlController ?>/listar/txtBuscar/'+txtBuscar+'/padre_id/<?php echo $this->objPadre->id ?>',page:1}).trigger("reloadGrid");
    }

    function editaDesdeLink(id){

        <?php if($this->editarSinDialog): ?>

            document.location = '<?php echo $this->baseUrlController ?>/editar/id/'+id;

        <?php else: ?>

            /* Asigno nuevo Título a la ventana que se abrirá */
            $("#wndEdicion").dialog("option", "title", '<?php echo $this->titulo ?> [Edición]');

            /* Cargo en el div la página que deseo */
            $("#wndEdicion").load('<?php echo $this->baseUrlController ?>/editar/id/'+id);

            /* Abro la ventana */
            setTimeout(function(){ $("#wndEdicion").dialog('open') }, 100);

        <?php endif; ?>

    }

    $(function() {

        /* Focus en Búsqueda */
        $("#txtBusqueda").focus();

        /* Para activar búsquedas con tecla enter */
        $("#txtBusqueda").keypress(function(e){
            if (e.which == 13) { /* Si ha presionado la tecla enter */
                gridReload();
            }
        });

        /* Agrego en la barra inferior solo el botón Recargar */
        jQuery("#list").jqGrid('navGrid','#pager',{edit:false,add:false,del:false,search:false});

        /* Configuro la ventana de Edición */
        $("#wndEdicion").dialog({
                title: "Edición",
                modal: true,
                autoOpen: false,
                width: <? echo $this->widthDialog; ?>,
                height: 'auto',
                buttons: {
                    Cerrar: function() {
                        $(this).text(""); 
			$(this).dialog('close');
                    }
		}
         });

        /* Asgino métodos a los botones */
        /* Botón Nuevo */
        // Para llamar al formulario en una página normal sin ventana Dialog.
        // en el action 'agregar' debe colocarse comentario a la línea $this->_helper->layout->disableLayout();
	// $("#btnNew").click(function() {
        //    document.location = '<?php // echo $this->baseUrlController ?>/agregar/';
        // });

        /* Botón Nuevo */
	$("#btnNew").click(function() {
            
            <?php if($this->editarSinDialog): ?>

                document.location = '<?php echo $this->baseUrlController ?>/agregar/';

            <?php else: ?>

                $("#wndEdicion").text(""); 

                /* Asigno nuevo Título a la ventana que se abrirá */
                $("#wndEdicion").dialog("option", "title", '<?php echo $this->titulo ?> [Nuevo]');

                /* Cargo en el div la página que deseo */
                $("#wndEdicion").load('<?php echo $this->baseUrlController ?>/agregar/padre_id/<?php echo $this->objPadre->id ?>');

                /* Abro la ventana */
                setTimeout(function(){ $("#wndEdicion").dialog('open') }, 100);

            <?php endif; ?>
            
        });

	$("#btnEdt").click(function() {
            var id = jQuery("#list").jqGrid('getGridParam','selrow');
            if( id != null ) {

                <?php if($this->editarSinDialog): ?>

                    document.location = '<?php echo $this->baseUrlController ?>/agregar/';

                <?php else: ?>

                    $("#wndEdicion").text(""); 

                     /* Asigno nuevo Título a la ventana que se abrirá */
                    $("#wndEdicion").dialog("option", "title", '<?php echo $this->titulo ?> [Editar]');

                    /* Cargo en el div la página que deseo */
                    $("#wndEdicion").load('<?php echo $this->baseUrlController ?>/editar/id/'+id);

                    /* Abro la ventana */
                    setTimeout(function(){ $("#wndEdicion").dialog('open') }, 100);

                <?php endif; ?>
            } else {
                MyAlert("Seleccione el registro a Editar!");
            }

        });

        /* Botón Eliminar */
        $("#btnDel").click(function(){
                var arrSelected = jQuery("#list").jqGrid('getGridParam','selarrrow'); /* Devuelve array con los id de todos los registros seleccionados */
                if( arrSelected.length > 0 ) {
                    jQuery("#list").jqGrid('delGridRow',arrSelected,{reloadAfterSubmit:false, url:'<?php echo $this->baseUrlController ?>/eliminar/', width: 400, height: 120,
                                        closeOnEscape:true,
                                        afterSubmit:function(data_from_server){  /* Función que se ejecuta "después de hacer el submir".  Recibe datos desde el server */
                                                var result=data_from_server.responseText.split("|");
                                                if (result[0] == "error"){
                                                    return [false,result[1]] /* No elimina el registro del grid y muestra un mensaje */
                                                } else {
                                                    return [true,result[1]]; /* Si elimina el regisro del grid y muestra un mensaje */
                                                }
                                        }
                    }); /* Elimina todos los registros seleccionados */

                } else {
                    MyAlert("Seleccione el(los) registro(s) a eliminar!");
                }
        });

    });

</script>
<div id="wndEdicion"></div>